[package]
name = "image_difference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
colorgrad = "0.6"

[[bin]]
name = "image_difference"
path = "src/image_diff.rs"